### ISSUE TITLE
DB driver is always overwritten, using dbal4 is not possible

### ISSUE THREAD

**Issue by DavidBadura** [symfony-cli/symfony-cli#539] opened 2024-11-22 12:02 UTC
## Problem

When using Symfony CLI with `doctrine/dbal` v4, there is the problem that the driver is hardcoded to "postgres". However, this driver can no longer be used in dbal 4:

```
The given driver "postgres" is unknown, Doctrine currently supports only the following drivers: 
pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_sqlsrv, mysqli, pgsql, sqlsrv, sqlite3
```

Here is the documentation on how to specify the connection with dbal4:

https://www.doctrine-project.org/projects/doctrine-dbal/en/4.3/reference/configuration.html#connecting-using-a-url

I don't know if you can force the driver into the .env. I looked at the code and don't see a workaround:

https://github.com/symfony-cli/symfony-cli/blob/main/envs/envs.go#L132

## Environment

In the .env I specified the following:

```ini
EVENTSTORE_URL="pdo-pgsql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=16&charset=utf8"
```

symfony var:export 

```ini
PGPASSWORD=!ChangeMe! 
PGPORT=58142 
SYMFONY_APPLICATION_DEFAULT_ROUTE_PORT=8000 
SYMFONY_APPLICATION_DEFAULT_ROUTE_PATH=/ 
SYMFONY_PROJECT_DEFAULT_ROUTE_HOST=127.0.0.1:8000 
PGDATABASE=app 
EVENTSTORE_PORT=58142 
SYMFONY_DOCKER_ENV=1 
SYMFONY_DEFAULT_ROUTE_SCHEME=http 
SYMFONY_PROJECT_DEFAULT_ROUTE_URL=http://127.0.0.1:8000/ 
SYMFONY_DEFAULT_ROUTE_URL=http://127.0.0.1:8000/ 
EVENTSTORE_DATABASE=app 
PGHOST=127.0.0.1 
SYMFONY_TUNNEL_BRAND= 
SYMFONY_DEFAULT_ROUTE_PATH=/ 
SYMFONY_TUNNEL_ENV= 
EVENTSTORE_USERNAME=app 
EVENTSTORE_PASSWORD=!ChangeMe! 
EVENTSTORE_HOST=127.0.0.1 
EVENTSTORE_DRIVER=postgres 
SYMFONY_DEFAULT_ROUTE_PORT=8000 
SYMFONY_DEFAULT_ROUTE_HOST=127.0.0.1:8000 
SYMFONY_APPLICATION_DEFAULT_ROUTE_HOST=127.0.0.1:8000 
SYMFONY_TUNNEL= 
SYMFONY_PROJECT_DEFAULT_ROUTE_PORT=8000 
SYMFONY_PROJECT_DEFAULT_ROUTE_SCHEME=http 
EVENTSTORE_USER=app 
EVENTSTORE_URL=postgres://app:!ChangeMe!@127.0.0.1:58142/app?sslmode=disable&charset=utf8&serverVersion=16.5 
EVENTSTORE_SERVER=postgres://127.0.0.1:58142 
EVENTSTORE_NAME=app 
SYMFONY_APPLICATION_DEFAULT_ROUTE_URL=http://127.0.0.1:8000/ 
SYMFONY_APPLICATION_DEFAULT_ROUTE_SCHEME=http 
SYMFONY_PROJECT_DEFAULT_ROUTE_PATH=/ 
EVENTSTORE_VERSION=16.5 
PGUSER=app%    
```

## Solution:

If you take a closer look at `EVENTSTORE_URL`, you can see that `pdo-pgsql` has been replaced by `postgres`. I don't understand why the driver is being hard-coded. My solution would be to always leave the driver as the user specified.

**Comment by tucksaun** [comment] 2024-11-23 13:41
I'm surprised because I use DBAL 4 on a project and it works without any issue for me.
Do you have a reproducer app available?

Also, to be noted, the DSN scheme is not exactly the same as the driver Doctrine is using: the DSN parser is doing some transformation and a mapping to retrieve the actual driver.

Finally, we don't parse the DSN defined in the `.env` file to adjust it. Instead we specify the full DSN (as you can see in the `var:export` output).
If really needed (but the best cours of action is to make it work/fix it), you should be able to force the driver in Doctrine configuration, or you can build the DSN using the different variables exposed by the CLI (ie. using something like `"pdo-pgsql://%(PGUSER)%:%env(PGPASSWORD)%@%env(DATABASE_HOST)%:%env(DATABASE_PORT)%/%env(PGDATABASE)%?serverVersion=16&charset=utf8"`)

**Comment by DavidBadura** [comment] 2024-11-24 10:55
Here you can find the reproducible app: https://github.com/patchlevel/event-sourcing-symfony

I did the following:

```bash
symfony new event-sourcing-symfony
cd event-sourcing-symfony
composer require patchlevel/event-sourcing-bundle
docker compose up -d
symfony server:start
```


---

I went down the rabbit hole and now I know why it works with doctrine-bundle. You can define a mapping in the query parser, which was not done with our event-sourcing library:

https://www.doctrine-project.org/projects/doctrine-dbal/en/4.2/reference/configuration.html#using-the-dsn-parser

This means that with doctrine-bundle you can use postgres as a driver, which is then mapped to pdo-pgsql. We can also get around the problem on our side and define the mapping there too.

So the ticket is closed for me. Thank you very much!

**Comment by tucksaun** [comment] 2024-11-24 11:47
Good news that you find out the issue 🙂 

Maybe the mapping should be moved to DBAL instead of Doctrine Bundle? I will let you have the discussion with Doctrine's team 😅 

As of now you are the only user who reported any issue with this so I will close the issue.
To any one in the future encountering the same issue, please let yourself know so that we can track if we must change the scheme part of the DSN.

**Closed by tucksaun** 2024-11-24 11:47 UTC
