### ISSUE TITLE
Chunked transfer encoding is not supported for web server?

### ISSUE THREAD

**Issue by rmikalkenas** [symfony-cli/symfony-cli#169] opened 2022-08-10 13:03 UTC
Hi! Could it be that `Transfer-Encoding: chunked` is not supported by a local web server?
If I'm passing form data body as string - then it works as expected, but the headers are different, because of known body size

Reproducer:

```
// request.php
$httpClient = HttpClient::create();
Assert::isInstanceOf($httpClient, CurlHttpClient::class);

$formData = new FormDataPart(
    [
        'files' => [
            new DataPart(\fopen(__DIR__ . '/image.png', 'r'), 'image.png'),
        ],
    ]
);

$response = $httpClient->request(
    'POST',
    'http://127.0.0.1:8000',
    [
        'headers' => $formData->getPreparedHeaders()->toArray(),
        'body' => $formData->bodyToString(),
    ]
);

// {"files":0} with $formData->bodyToIterable()
// {"files":1} with $formData->bodyToString()
$response->getContent();
```

```
// index.php
require_once \dirname(__DIR__) . '/vendor/autoload.php';

$request = Request::createFromGlobals();

$allFiles = $request->files->all();

$response = new JsonResponse(['files' => count($allFiles)]);
$response->send();
```

**Comment by tucksaun** [comment] 2022-08-10 14:31
after some investigation, the Golang HTTP server automatically translates chunked encoding for us (which is good because CGI does not support chunk encoding) but because this is transferred as chunked we don't have a content-length header so PHP discards the body.

the solution would be to buffer the body, get its length and add the content-length header accordingly. the issue is that it could increase the server memory usage if a large file is sent. potentially it could also slow things down a bit 🤔

**Comment by tucksaun** [comment] 2023-02-13 22:17
Hey @rmikalkenas 

I completely forgot but I have a patch here: https://github.com/tucksaun/symfonycli/tree/fix-chunked-transfer-encoding
could you give it a try?

thanks

**Closed** 2024-01-03 06:42 UTC

**Comment by tucksaun** [comment] 2024-01-23 08:31
@rmikalkenas why closing? is the patch I provided not working? or is it now working?

**Comment by ysipd26020** [comment] 2024-02-13 22:38
> @rmikalkenas why closing? is the patch I provided not working? or is it now working?

I'm curious too. I am running into this same issue with my own environment and this fix would be quite useful.

**Comment by tucksaun** [comment] 2024-02-14 07:57
ok then let's open the PR and see if it works for you

**Comment by tucksaun** [comment] 2024-02-14 08:46
@ysipd26020 see #437

**Comment by fabpot** [comment] 2024-03-13 16:31
Fixed now
