### ISSUE TITLE
Upgrading to 5.8.6 causes invalid MariaDB version string in local docker environment

### ISSUE THREAD

**Issue by Jontsa** [symfony-cli/symfony-cli#425] opened 2024-02-05 11:15 UTC
For development, we are using MariaDB 10.6 in docker container and Symfony CLI to serve pages. After upgrading to Symfony CLI 5.8.6, we started seeing deprecation warnings like this from Doctrine:

`MySQL 5.6 support is deprecated and will be removed in DBAL 4. Consider upgrading to MySQL 5.7 or later.`

It looks like 5.8.6 is unable to parse the version string from MariaDB server correctly. If I debug $_ENV["DATABASE_URL"], it shows `mysql://***:***@127.0.0.1:32769/***?sslmode=disable&charset=utf8mb4&serverVersion=1:10.6.15+maria~ubu2004` and 
AbstractMySQLDriver receives version string `1:10.6.15 maria~ubu2004`.

Downgrading to 5.8.4 fixes the issue.

## How to reproduce

docker-compose.yml
```yaml
version: '3.7'

services:
  database:
    container_name: database
    image: mariadb:10.6
...
```

.env
```env
###> doctrine/doctrine-bundle ###
DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/sirukyc?serverVersion=10.6.11-MariaDB
###< doctrine/doctrine-bundle ###
```

config/packages/doctrine.yaml
```yaml
doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                profiling_collect_backtrace: '%kernel.debug%'
                url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
```

How MariaDB reports version string

```bash
$ docker compose exec database mysql -uroot -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 106
Server version: 10.6.15-MariaDB-1:10.6.15+maria~ubu2004 mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> 
```
```bash
$ docker compose exec database mysql --version
mysql  Ver 15.1 Distrib 10.6.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by Jontsa** [comment] 2024-02-05 11:21
Not related but another issue we noticed while investigating this:

Forcing the database version in `doctrine.dbal.server_version` would fix the issue but because we are using multiple database connections, we need to use path `doctrine.dbal.connections.default.server_version`. Setting the database version here is not detected by Symfony CLI.

**Comment by jmsche** [comment] 2024-02-07 12:35
I'm having the same issue here.

Not sure how setting `doctrine.dbal.server_version` would "fix" anything because it does not on my projects (one database only).

**Comment by jmsche** [comment] 2024-02-07 12:51
Here is a reproducer (I guess not all steps are required):

```
git clone https://github.com/symfony/demo.git
cd demo
composer i
echo -e "version: '3'\nservices:\n  database:\n    image: mariadb:10.6\n    restart: always\n    environment:\n      MARIADB_ROOT_PASSWORD: root\n      MARIADB_DATABASE: demo\n    ports: [3306]" > compose.yaml
docker compose up -d && symfony serve -d
symfony console d:s:u -f --complete
symfony var:export DATABASE_URL
```

The last command returns something like `mysql://root:root@127.0.0.1:32783/demo?sslmode=disable&charset=utf8mb4&serverVersion=1:10.6.16+maria~ubu2004`

**Comment by fabpot** [comment] 2024-02-07 13:03
@jmsche This has been fixed in 5.8.6 (I've just tested).

**Comment by Lustmored** [comment] 2024-02-07 13:19
@fabpot I have also encountered this problem and it is exactly with version 5.8.6 - for me database version is reported as `1:11.2.2+maria~ubu2204`

**Comment by jmsche** [comment] 2024-02-07 13:21
It's weird, I reupdated to 5.8.6 & get a correct serverVersion... Not sure what is happening here :/

**Comment by Lustmored** [comment] 2024-02-07 13:25
At least `brew reinstall symfony-cli` on linux doesn't change anything for me :cry:

**Comment by Wait4Code** [comment] 2024-02-07 13:34
> At least `brew reinstall symfony-cli` on linux doesn't change anything for me 😢

Same with apt here (Ubuntu 22.04.3 LTS)

**Comment by Jontsa** [comment] 2024-02-07 13:40
Same with Ubuntu 23.04. Tried purging and re-installing symfony-cli using Apt but it did not help

```
$ symfony
Symfony CLI version 5.8.6 (c) 2021-2024 Fabien Potencier (2024-01-30T13:12:32Z - stable)

$ symfony var:export DATABASE_URL
mysql://***:***@127.0.0.1:32769/***?sslmode=disable&charset=utf8mb4&serverVersion=1:10.6.15+maria~ubu2004
```

**Comment by nicolas-grekas** [comment] 2024-02-09 13:30
When I run docker compose up, one of the first line I see is:
> database  | 2024-02-09 13:23:30+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.16+maria~ubu2004 started.

It contains the buggy version number. This is a line from docker itself so not involving the symfony binary.
At this stage, it looks like a bug in docker. We can work around it of course, as a hack.
Anyone would have more background on the topic?

**Comment by nicolas-grekas** [comment] 2024-02-09 13:36
Looks like the version comes from this line:
https://github.com/MariaDB/mariadb-docker/blob/b1fff513e7b7d015c5cfb2d91ffc24d903d33434/10.6/Dockerfile#L84

So we can safely remove the `1:`, isn't it?

**Closed** 2024-02-09 13:46 UTC
