### ISSUE TITLE
mkdir /.symfony5: permission denied

### ISSUE THREAD

**Issue by roukmoute** [symfony-cli/symfony-cli#185] opened 2022-09-17 23:00 UTC
Hi,

I have this problem with Symfony CLI, do you have any idea?

```sh
$ symfony -V
Disabling update check: "mkdir /.symfony5: permission denied"
Symfony CLI version 5.4.13 (c) 2017-2022 Symfony SAS #StandWithUkraine Support Ukraine (2022-08-16T08:17:04Z - stable)
$ symfony new test
Disabling update check: "mkdir /.symfony5: permission denied"
* Creating a new Symfony project with Composer
  (running /usr/bin/composer create-project symfony/skeleton /app/test  --no-interaction)

mkdir /.symfony5: permission denied

                                                                                               
  unable to run /usr/bin/composer create-project symfony/skeleton /app/test  --no-interaction  
                                                                                               
$ /usr/bin/composer create-project symfony/skeleton /app/test  --no-interaction
Creating a "symfony/skeleton" project at "./test"
Info from https://repo.packagist.org: #StandWithUkraine
Installing symfony/skeleton (v6.1.99)
  - Downloading symfony/skeleton (v6.1.99)
  - Installing symfony/skeleton (v6.1.99): Extracting archive
[...](Everything works fine)

  * Read the documentation at https://symfony.com/doc
$ 
```

**Comment by tucksaun** [comment] 2022-09-27 16:47
hi @roukmoute,

it looks like the CLI does not manage to detect your home directory...
can you give more information about your system so we can understand why?
thanks

**Comment by roukmoute** [comment] 2022-10-02 22:21
I try to run symfony cli in Docker.

Now it works with:

```sh
docker run --rm --user "1000:1001" --mount type=bind,source="$HOME"/,target=$HOME --mount type=bind,source="$(pwd)"/,target=/app --workdir=/app --network=host --env HOME=$HOME -ti roukmoute/symfony-cli sh
```

Do you have any suggestion/optimization?

**Comment by tucksaun** [comment] 2022-10-02 22:38
I should mention I would recommend to think again about it as the whole purpose of the CLI is to work with local PHP setups and optionally **with** Docker but not **in** Docker.

But I still tried to reproduce your issue with the provided Docker command without any luck.
So maybe this is due to your specific Docker image (are you able to share it?) or your Docker daemon setup?e

**Comment by fabpot** [comment] 2023-02-24 08:17
Closing as there is no more activity.

**Closed by fabpot** 2023-02-24 08:17 UTC
